import './globals.css';
import 'react-loading-skeleton/dist/skeleton.css';
import 'simplebar-react/dist/simplebar.min.css';

import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import ModalProvider from '@/components/ModalProvider';
import Navbar from '@/components/Navbar';
import Providers from '@/components/Providers';
import { Toaster } from '@/components/ui/toaster';
import { twMerge } from 'tailwind-merge';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Pagebot',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" className="light">
            <Providers>
                <body
                    className={twMerge(
                        inter.className,
                        'min-h-screen font-sans antialiased grainy'
                    )}
                >
                    <ModalProvider />
                    <Toaster />
                    <Navbar />
                    {children}
                </body>
            </Providers>
        </html>
    );
}
